// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa0tDo0_E00eCme5f-jR2ZHH3l7nh0eS0',
    appId: '1:207455730121:web:c50a7b80a760858e589018',
    messagingSenderId: '207455730121',
    projectId: 'studyplanner-31a8c',
    authDomain: 'studyplanner-31a8c.firebaseapp.com',
    storageBucket: 'studyplanner-31a8c.firebasestorage.app',
    measurementId: 'G-4W1HMV0DEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-pFV8uWAHwVG0Vcq4KrYWNjGWlWPKGjo',
    appId: '1:207455730121:android:833b78b866538cf4589018',
    messagingSenderId: '207455730121',
    projectId: 'studyplanner-31a8c',
    storageBucket: 'studyplanner-31a8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzFUOzJll9vQDfnDDVGof18Y2ZhtjgGbA',
    appId: '1:207455730121:ios:e2c0c52eff10b741589018',
    messagingSenderId: '207455730121',
    projectId: 'studyplanner-31a8c',
    storageBucket: 'studyplanner-31a8c.firebasestorage.app',
    iosBundleId: 'com.studyplanner.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzFUOzJll9vQDfnDDVGof18Y2ZhtjgGbA',
    appId: '1:207455730121:ios:e2c0c52eff10b741589018',
    messagingSenderId: '207455730121',
    projectId: 'studyplanner-31a8c',
    storageBucket: 'studyplanner-31a8c.firebasestorage.app',
    iosBundleId: 'com.studyplanner.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa0tDo0_E00eCme5f-jR2ZHH3l7nh0eS0',
    appId: '1:207455730121:web:23ac0ceff6f27a03589018',
    messagingSenderId: '207455730121',
    projectId: 'studyplanner-31a8c',
    authDomain: 'studyplanner-31a8c.firebaseapp.com',
    storageBucket: 'studyplanner-31a8c.firebasestorage.app',
    measurementId: 'G-2DFVSY43Q8',
  );
}
